### ISSUE TITLE
Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by Buzzertech** [marcelodolza/iziModal#141]
I'm using iziModal in one of my project (I have used it in the past as well). I'm constantly getting the below error in the console:
`Uncaught TypeError: Cannot read property 'split' of undefined
    at r.fn.init.t.fn.(anonymous function) [as iziModal] (https://cdnjs.cloudflare.com/ajax/libs/izimodal/1.5.1/js/iziModal.min.js:6:23583)
    at Object.success (http://localhost/MT/main.js:57:30)
    at i (https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js:2:28017)
    at Object.fireWith [as resolveWith] (https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js:2:28783)
    at A (https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js:4:14035)
    at XMLHttpRequest.<anonymous> (https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js:4:16323)`

Any help would be appreciated :)

**Comment by Dan-Ross** [comment]
We're updating a project that used iziModal as well, and the only thing I can see that's different is that we're using a newer version of jQuery (3.2.1) instead of 1.9.1.

I'm getting a near identical error and can't find out why. 
@Buzzertech did you ever find a solution?

**Comment by hamedgasemi200** [comment]
I have same error , I don't know what's the problem ... I hope someone fix it

**Comment by evbermudez** [comment]
you may have initialized iziModal and the element that you are targeting doesn't exist on the current page.
